<?php
/**
 * Setting Lexicon Entries for TinyMCE Rich Text Editor
 *
 * @package tinymcerte
 * @subpackage lexicon
 */
$_lang['area_modai'] = 'modAI';
$_lang['area_tinymcerte.default'] = 'TinyMCE';
$_lang['area_tinymcerte.style_formats'] = 'Style Formats';
$_lang['area_tinymcerte.toolbar'] = 'Toolbar';
$_lang['setting_tinymcerte.alignment_format'] = 'Alignment format';
$_lang['setting_tinymcerte.alignment_format_desc'] = 'This option enables you to add more advanced style formats for text and other elements to the editor. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats">https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats</a>';
$_lang['setting_tinymcerte.blocks_format'] = 'Blocks format';
$_lang['setting_tinymcerte.blocks_format_desc'] = 'This option enables you to add more advanced style formats for text and other elements to the editor. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats">https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats</a>';
$_lang['setting_tinymcerte.browser_spellcheck'] = 'Spellcheck';
$_lang['setting_tinymcerte.browser_spellcheck_desc'] = 'Enable or disable browser spellscheck. <a href="https://www.tiny.cloud/docs/configure/spelling/#browser_spellcheck">https://www.tiny.cloud/docs/configure/spelling/#browser_spellcheck</a>';
$_lang['setting_tinymcerte.content_css'] = 'Content CSS';
$_lang['setting_tinymcerte.content_css_desc'] = 'Load additional CSS files with TinyMCE. Use "," (comma) delimiter for multiple files. <a href="https://www.tiny.cloud/docs/configure/content-appearance/#content_css">https://www.tiny.cloud/docs/configure/content-appearance/#content_css</a>';
$_lang['setting_tinymcerte.enable_link_list'] = 'Enable link list';
$_lang['setting_tinymcerte.enable_link_list_desc'] = 'This option enables the nested link list in the link plugin. It can be switched off, when the link list creates a timeout on very large sites.';
$_lang['setting_tinymcerte.enable_link_aria'] = 'Enable link Aria';
$_lang['setting_tinymcerte.enable_link_aria_desc'] = 'This option enables the aria-label and aria-labelledby attributes for the link plugin. It can be switched off, however if aria attributes are detected on a link it will show the fields anyway.';
$_lang['setting_tinymcerte.external_config'] = 'External config';
$_lang['setting_tinymcerte.external_config_desc'] = 'Path to an external JSON config file. It will be merged with with the system setting defaults.';
$_lang['setting_tinymcerte.headers_format'] = 'Headers format';
$_lang['setting_tinymcerte.headers_format_desc'] = 'This option enables you to add more advanced style formats for text and other elements to the editor. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats">https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats</a>';
$_lang['setting_tinymcerte.image_advtab'] = 'Advanced tab for images';
$_lang['setting_tinymcerte.image_advtab_desc'] = 'This option enables the advanced tab the image dialog allowing you to add custom styles to images. <a href="https://www.tiny.cloud/docs/plugins/opensource/image/#image_advtab">https://www.tiny.cloud/docs/plugins/opensource/image/#image_advtab</a>';
$_lang['setting_tinymcerte.image_class_list'] = 'Image class list';
$_lang['setting_tinymcerte.image_class_list_desc'] = 'Class list for images. <a href="https://www.tiny.cloud/docs/plugins/opensource/image/#image_class_list">https://www.tiny.cloud/docs/plugins/opensource/image/#image_class_list</a>';
$_lang['setting_tinymcerte.inline_format'] = 'Inline format';
$_lang['setting_tinymcerte.inline_format_desc'] = 'This option enables you to add more advanced style formats for text and other elements to the editor. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats">https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats</a>';
$_lang['setting_tinymcerte.link_class_list'] = 'Link class list';
$_lang['setting_tinymcerte.link_class_list_desc'] = 'Class list for links. <a href="https://www.tiny.cloud/docs/plugins/opensource/link/#link_class_list">https://www.tiny.cloud/docs/plugins/opensource/link/#link_class_list</a>';
$_lang['setting_tinymcerte.links_across_contexts'] = 'Links across contexts';
$_lang['setting_tinymcerte.links_across_contexts_desc'] = 'Lists resources from other contexts when creating internal links in the editor. Otherwise only Resources from the same context appear.';
$_lang['setting_tinymcerte.max_height'] = 'Max height';
$_lang['setting_tinymcerte.max_height_desc'] = 'The max_height option has two kinds of behaviors depending on the state of the autoresize plugin. Without the autoresize plugin, this option allows you to set the maximum height that a user can stretch the entire TinyMCE interface (by grabbing the draggable area in the bottom right of the editor interface). With the autoresize plugin, this option sets the maximum height the editor can automatically expand to.';
$_lang['setting_tinymcerte.min_height'] = 'Min height';
$_lang['setting_tinymcerte.min_height_desc'] = 'The min_height option has two kinds of behaviors depending on the state of the autoresize plugin. Without the autoresize plugin, this option allows you to set the minimum height that a user can shrink the entire TinyMCE interface (by grabbing the draggable area in the bottom right of the editor interface). With the autoresize plugin, this option sets the minimum height the editor can automatically shrink to.';
$_lang['setting_tinymcerte.menubar'] = 'Menubar';
$_lang['setting_tinymcerte.menubar_desc'] = 'This option allows you to configure the menus you want to appear in the menu bar. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#menubar">https://www.tiny.cloud/docs/configure/editor-appearance/#menubar</a>';
$_lang['setting_tinymcerte.modai.global.text.base_prompt'] = 'Base Prompt';
$_lang['setting_tinymcerte.modai.global.text.base_prompt_desc'] = 'This is an overall instruction modifier that is added to each API request by default, similar to what you would enter for Customize ChatGPT on their website.';
$_lang['setting_tinymcerte.modai.global.text.modify_prompts'] = 'Modify Prompts';
$_lang['setting_tinymcerte.modai.global.text.modify_prompts_desc'] = 'This is a JSON configuration that defines prompts for each category and menu option. Feel free to add or change languages, styles, tones, or any other options.';
$_lang['setting_tinymcerte.object_resizing'] = 'Object resizing';
$_lang['setting_tinymcerte.object_resizing_desc'] = 'This options allows you to turn on/off the resizing handles on images, tables or media objects. <a href="https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#object_resizing">https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#object_resizing</a>';
$_lang['setting_tinymcerte.paste_as_text'] = 'Paste as text';
$_lang['setting_tinymcerte.paste_as_text_desc'] = 'This option enables you to set the default state of the "paste as text" edit menu option. <a href="https://www.tiny.cloud/docs/plugins/opensource/paste/#paste_as_text">https://www.tiny.cloud/docs/plugins/opensource/paste/#paste_as_text</a>';
$_lang['setting_tinymcerte.plugins'] = 'Plugins';
$_lang['setting_tinymcerte.plugins_desc'] = 'Set which plugins are loaded (None are loaded by default). <a href="https://www.tiny.cloud/docs/configure/integration-and-setup/#plugins">https://www.tiny.cloud/docs/configure/integration-and-setup/#plugins</a>';
$_lang['setting_tinymcerte.relative_urls'] = 'Relative URLs';
$_lang['setting_tinymcerte.relative_urls_desc'] = 'If this option is set to true, all URLs starting with the URL in the MODX site_url system setting will be converted to a relative URL to this site_url. If it’s set to false all URLs will be converted to absolute URLs (see remove_script_host for additional options in that case).';
$_lang['setting_tinymcerte.remove_script_host'] = 'Remove script host';
$_lang['setting_tinymcerte.remove_script_host_desc'] = 'Removes the protocol and host part of URLs returned from the MODX file browser (Only used if relative_urls is off).';
$_lang['setting_tinymcerte.settings'] = 'Additional settings';
$_lang['setting_tinymcerte.settings_desc'] = 'JSON-encoded object of additional TinyMCE settings.';
$_lang['setting_tinymcerte.skin'] = 'Skin';
$_lang['setting_tinymcerte.skin_desc'] = 'This option allows you to specify the skin that TinyMCE should use. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#skin">https://www.tiny.cloud/docs/configure/editor-appearance/#skin</a>';
$_lang['setting_tinymcerte.statusbar'] = 'Statusbar';
$_lang['setting_tinymcerte.statusbar_desc'] = 'This option allows you to specify whether TinyMCE should display the status bar at the bottom of the editor. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#statusbar">https://www.tiny.cloud/docs/configure/editor-appearance/#statusbar</a>';
$_lang['setting_tinymcerte.style_formats'] = 'Style formats';
$_lang['setting_tinymcerte.style_formats_desc'] = 'This option enables you to add more advanced style formats for text and other elements to the editor. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats">https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats</a>';
$_lang['setting_tinymcerte.style_formats_merge'] = 'Merge style formats';
$_lang['setting_tinymcerte.style_formats_merge_desc'] = 'If you want to merge your styles to the default styles_format. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats">https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats</a>';
$_lang['setting_tinymcerte.toolbar1'] = 'Toolbar 1';
$_lang['setting_tinymcerte.toolbar1_desc'] = 'This controls what buttons you want show up in the toolbar. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar">https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar</a>';
$_lang['setting_tinymcerte.toolbar2'] = 'Toolbar 2';
$_lang['setting_tinymcerte.toolbar2_desc'] = 'This controls what buttons you want show up in the toolbar. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar">https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar</a>';
$_lang['setting_tinymcerte.toolbar3'] = 'Toolbar 3';
$_lang['setting_tinymcerte.toolbar3_desc'] = 'This controls what buttons you want show up in the toolbar. <a href="https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar">https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar</a>';
$_lang['setting_tinymcerte.valid_elements'] = 'Valid elements';
$_lang['setting_tinymcerte.valid_elements_desc'] = 'This option defines which elements will remain in the edited text when the editor saves. You can use this to limit the returned HTML to a subset. <a href="https://www.tiny.cloud/docs/configure/content-filtering/#valid_elements">https://www.tiny.cloud/docs/configure/content-filtering/#valid_elements</a>.';
$_lang['setting_tinymcerte.selection_toolbar'] = 'Selection Toolbar';
$_lang['setting_tinymcerte.selection_toolbar_desc'] = 'This option defines what is shown in the toolbar when selecting text. <a href="https://www.tiny.cloud/docs/tinymce/latest/quickbars/#quickbars_selection_toolbar">https://www.tiny.cloud/docs/tinymce/latest/quickbars/#quickbars_selection_toolbar</a>.';
$_lang['setting_tinymcerte.insert_toolbar'] = 'Insert Toolbar';
$_lang['setting_tinymcerte.insert_toolbar_desc'] = 'This option defines what is shown in the toolbar when the cursor is at the start of an empty line. <a href="https://www.tiny.cloud/docs/tinymce/latest/quickbars/#quickbars_insert_toolbar">https://www.tiny.cloud/docs/tinymce/latest/quickbars/#quickbars_insert_toolbar</a>.';
$_lang['setting_tinymcerte.tiny_url'] = 'TinyMCE URL';
$_lang['setting_tinymcerte.tiny_url_desc'] = 'The URL or path to the TinyMCE JavaScript file.';
$_lang['setting_tinymcerte.lit'] = 'Last Install Time';
$_lang['setting_tinymcerte.lit_desc'] = 'Last package install in unix time for cache busting.';
